# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "weekly"
    # Optional: Define custom commit message for updates
    commit-message:
      prefix: "fix"
      suffix: "dependency updates"
    versioning-strategy: "increase"

  # This section can be used to update devDependencies separately
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "weekly"
    dependency-type: "dev"
    commit-message:
      prefix: "chore"
      suffix: "dev dependencies"
    versioning-strategy: "increase"

