// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	NEXT_CACHE_WORKERS_KV: KVNamespace;
	NEXTJS_ENV: string;
	GOOGLE_SHEETS_API_URL: string;
	GOOGLE_SHEETS_API_TOKEN: string;
	RECAPTCHA_SECRET_KEY: string;
	NEXT_PUBLIC_RECAPTCHA_SITE_KEY: string;
	GOOGLE_SHEETS_SPREADSHEET_ID: string;
	CONTENTFUL_SPACE_ID: string;
	CONTENTFUL_ACCESS_TOKEN: string;
	SUMOBOTS_API_KEY: string;
	ASSETS: Fetcher;
}
