// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	SB_NEXT_CACHE_WORKERS_KV: KVNamespace;
	NEXTJS_ENV: string;
	NEXT_PUBLIC_RECAPTCHA_SITE_KEY: string;
	SUMOBOTS_WORKER_KEY: string;
	ASSETS: Fetcher;
}
