/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "CONTENTFUL_ACCESS_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CONTENTFUL_SPACE_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_SHEETS_API_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_SHEETS_API_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_SHEETS_SPREADSHEET_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_RECAPTCHA_SITE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RECAPTCHA_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ramsocSumobotsWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}