name: Pull Request

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  pr-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Request Title Linter
        uses: morrisoncole/pr-lint-action@v1.7.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title-regex: '^(feat|fix|docs|style|refactor|perf|test|chore)(\([^)]+\))?: .+$'
          on-failed-regex-fail-action: true
          on-failed-regex-create-review: true
          on-failed-regex-request-changes: false
          on-failed-regex-comment: "❌ The PR title should follow this format: `{type}: <description>`\n\nExamples:\n- `feat: add user login`\n- `fix(auth): handle expired token`"
          on-succeeded-regex-dismiss-review-comment: "✅ Awesome! The PR title is correct and matches the required format."
